### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by BathoryPeter** [yvecai/osmand-ski#3]
Hi Yves!

I've tried cloning your git for adding Hungarian translation, but I cannot push it back. git push gives me:
error: The requested URL returned error: 403 while accessing https://github.com/yvecai/osmand-ski.git/info/refs
I dont know what was my mistake, its was the first time I tried cloning git to my computer...

If you create values-hu with an empty strings.xml I will copy the translation via web interface.

Thanks,
Péter

**Comment by yvecai** [comment]
I created the values-hu with the english template in it.
When you fork on github, you can edit the file of your fork, then make a 'pull request' that I have to accept.

With a git clone on your desktop, I don't know how to do a pull request, there must be a way.
Yves

**Comment by yvecai** [comment]
No, in fact you can't: a 'pull request' is specific to github.

You need to give me access to your local repository in read access, and send me a mail so that I can pull. Maybe it's easier to fork on github.

**Comment by BathoryPeter** [comment]
Its strange, I cannot find values-hu. Neither in res folder, nor in your last commit: https://github.com/yvecai/osmand-ski/commit/1dd6953beab6382ffe3ec92509cb9f65b72c70ac where only OsmandskiActivity.java was changed.

I tried desktop clone just because I cannot create new folder in my repo which is forked from yours.

**Comment by yvecai** [comment]
Oups, sorry, I did not added the new files before commit. It's on github 
now.

Yves

**Comment by yvecai** [comment]
I now it's a pain when I don't master git, but anyway, you can just send 
me the file by email ;-)
Yves

**Comment by BathoryPeter** [comment]
Email would be too simple ;)

## I think this translation is not so urgent and a good time for me to understand how git works.

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

yvecai reply@reply.github.com írta:

I now it's a pain when I don't master git, but anyway, you can just send 
me the file by email ;-)
Yves

Le 05/02/2012 18:42, Báthory Péter a écrit :

> Its strange, I cannot find values-hu. Neither in res folder, nor in your last commit: https://github.com/yvecai/osmand-ski/commit/1dd6953beab6382ffe3ec92509cb9f65b72c70ac where only OsmandskiActivity.java was changed.
> 
> I tried desktop clone just because I cannot create new folder in my repo which is forked from yours.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yvecai/osmand-ski/issues/3#issuecomment-3819197

---

**Comment by yvecai** [comment]
That's probably the first goal of Osmand-ski: to learn git :)

**Comment by BathoryPeter** [comment]
Still I cannot push changes in command line, so I added translation via github.com.

Thanks for your patience!
